// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaWebZoologico.WEB.Models.DAL;

namespace PracticaWebZoologico.WEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticaWebZoologico.WEB.Models.Entities.Animal", b =>
                {
                    b.Property<int>("NombreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ColorAnimalColorId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("EspecieAnimalEspecieId")
                        .HasColumnType("int");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NombreId");

                    b.HasIndex("ColorAnimalColorId");

                    b.HasIndex("EspecieAnimalEspecieId");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("PracticaWebZoologico.WEB.Models.Entities.ColorAnimal", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("ColoresAnimales");
                });

            modelBuilder.Entity("PracticaWebZoologico.WEB.Models.Entities.EspecieAnimal", b =>
                {
                    b.Property<int>("EspecieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEspecie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecieId");

                    b.ToTable("EspeciesAnimales");
                });

            modelBuilder.Entity("PracticaWebZoologico.WEB.Models.Entities.Animal", b =>
                {
                    b.HasOne("PracticaWebZoologico.WEB.Models.Entities.ColorAnimal", "ColorAnimal")
                        .WithMany()
                        .HasForeignKey("ColorAnimalColorId");

                    b.HasOne("PracticaWebZoologico.WEB.Models.Entities.EspecieAnimal", "EspecieAnimal")
                        .WithMany()
                        .HasForeignKey("EspecieAnimalEspecieId");

                    b.Navigation("ColorAnimal");

                    b.Navigation("EspecieAnimal");
                });
#pragma warning restore 612, 618
        }
    }
}
